landscapeName: omp
landscapeMemberClasses:
   - name: Platinum Membership
     category: Platinum
   - name: End-User Membership
     category: Platinum
   - name: Silver Membership
     category: Silver
   - name: Academic Membership
     category: Academic Institution
   - name: Associate Membership
     category: Associate
project: a0941000002wBymAAE # Open Mainframe Project
landscapeMemberCategory: Open Mainframe Project Member Company
landscapefile: landscape.yml
missingcsvfile: missing.csv
